services:
  postgres:
    image: postgres:16
    container_name: gestion-admisiones-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: gestion_admisiones
      POSTGRES_USER: gestion_admisiones_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: